$(document).ready(function(){
    $('.header__burger').click(function(event){
        $('.header__burger,.header__menu').toggleClass('active');
        $('body').toggleClass('lock');
    });
});
$(document).ready(function(){
    $('.switch__button').click(function(event){
        if($('.switch__button').hasClass('click')){
            $('.switch__button').removeClass('click')
        }
        $(this).toggleClass('click')
    });
});